handle_args: char:1; exception: E1().
----------------
Coverage Report:

__main__: exc-TF_%s.py: 6 traceable; 6 covered; 0 ignored; 0 ignored but covered; 0 not covered.
